### ISSUE TITLE
[FYI] Two recommendation.

### ISSUE THREAD

**Issue by hiroyuki-sato** [kataring/embulk-plugin-google-spreadsheets#1]
Hello 

Thank you for contributing embulk-plugins. 

I recommend you the following.

* Separate input and output plugin. otherwise, this plugin does not list plugin list.
* Change plugin layout.

## Separate input and output plugin.

This is embulk plugin list page. this page list by category. 
That's why I recommend you separate input and output plugins. 
like embulk-input-google_spreadsheets and 
embulk-output-google_spreadsheets.

[List of Plugins by Category](http://www.embulk.org/plugins/) 

## Change plugin layout.

Due to plugin layout change (0.4.0>), latest embulik raise the following exception. 

I recommend you to change plugin layout. 

* input: lib/embulk/input/google_spreadsheets
* output: lib/ebulk/output/google_spreadsheets

```
embulk preview /tmp/test.yml
2015-04-21 10:48:20.289 +0900: Embulk v0.6.2
Embulk::PluginLoadError: Unknown input plugin 'google_spreadsheets'. embulk/input/google_spreadsheets.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
```

```
in:
  type: google_spreadsheets
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  refresh_token: YOUR_REFRESH_TOKEN
  url: 'https://docs.google.com/spreadsheets/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/edit#gid=0'
  columns:
    - { name: id, type: string }
    - { name: first_name, type: string }
    - { name: last_name,  type: string }
    - { name: nick_name,  type: string }
    - { name: birthday,   type: string }
out:
  type: google_spreadsheets
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  refresh_token: YOUR_REFRESH_TOKEN
  url: 'https://docs.google.com/spreadsheets/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/edit#gid=0'
  columns:
    - { name: id, type: string }
    - { name: first_name, type: string }
    - { name: last_name,  type: string }
    - { name: nick_name,  type: string }
    - { name: birthday,   type: string }
```

Please contact @hiroysato hiroysato at gmail.com (Japanese ok) if you need for more information.
